# Generated by Django 3.0 on 2020-05-10 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-name'], 'verbose_name_plural': 'cities'},
        ),
    ]
