# Generated by Django 3.0 on 2020-05-10 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_auto_20200510_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
    ]
